parameters:
  - name: repoUrl
    type: string
    default: 'https://github.com/QoT-Solutions/safeSpeed_BackEnd.git'
  - name: dockerUser
    type: string
    default: 'kopanomgn'
  - name: dockerPass
    type: string
    default: 'KopanoMagano@97'
  - name: dockerImage
    type: string
    default: 'testexec'
  - name: dockerTag
    type: string
    default: '1'

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  # - stage: CloneAndBuild
  #   displayName: 'Clone Repository and Execute Tasks'
  #   jobs:
  #     - job: CloneAndExecute
  #       steps:
  #         - script: echo "Cloning repository from ${{ parameters.repoUrl }}"
  #           displayName: 'Display Repo URL'
          
  #         - script: |
  #             git clone ${{ parameters.repoUrl }} repo
  #             cd repo
  #             echo "Add other tasks to build, test, and deploy your project."
  #             # Here you can add other git commands or any build/test/deploy scripts
  #           displayName: 'Clone repository and execute tasks'
  - stage: EchoStage
    displayName: 'Additional Echo Scripts'
    jobs:
      - job: EchoJob
        steps:
          - script: ls -al
            displayName: 'Echo Script 1'

          - script: echo "This is the second echo statement in the new stage."
            displayName: 'Echo Script 2'
  - stage: DockerBuildAndPush
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: DockerJob
        steps:
          - script: |
              echo "Logging in to Docker Hub"
              docker login --username ${{ parameters.dockerUser }} --password ${{ parameters.dockerPass }}
            displayName: 'Docker Login'
          
          - script: |
              echo "Building Docker image"
              # git clone ${{ parameters.repoUrl }} repo2
              cd repo2
              docker build ${{ parameters.repoUrl }} -t ${{ parameters.dockerUser }}/${{ parameters.dockerImage }}:${{ parameters.dockerTag }}
            displayName: 'Build Docker Image'

          - script: |
              echo "Pushing Docker image to Docker Hub"
              docker push ${{ parameters.dockerUser }}/${{ parameters.dockerImage }}:${{ parameters.dockerTag }}
            displayName: 'Push Docker Image to Docker Hub'

          - script: |
              echo "Docker image pushed successfully."
            displayName: 'Echo Success'